name: Create Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    build-linux-windows:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v4
              with:
                  go-version: "1.23"
                  cache: true

            - name: Install Linux dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    libx11-dev \
                    libxcursor-dev \
                    libxrandr-dev \
                    libxinerama-dev \
                    libxi-dev \
                    libgl1-mesa-dev \
                    libasound2-dev \
                    libxxf86vm-dev

            - name: Build Linux binary
              run: |
                  GOOS=linux GOARCH=amd64 go build -o g8emu cmd/desktop/main.go
                  chmod +x g8emu
                  zip g8emu-linux-amd64.zip g8emu
                  rm g8emu

            - name: Build Windows binary (cross-compile on Ubuntu)
              run: |
                  CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o g8emu.exe cmd/desktop/main.go
                  zip g8emu-windows-amd64.zip g8emu.exe
                  rm g8emu.exe

            - uses: actions/upload-artifact@v4
              with:
                  name: linux-windows
                  path: |
                      g8emu-linux-amd64.zip
                      g8emu-windows-amd64.zip

    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v4
              with:
                  go-version: "1.23"
                  cache: true

            - name: Build macOS binary (arm64)
              run: |
                  GOOS=darwin GOARCH=arm64 go build -o g8emu cmd/desktop/main.go
                  chmod +x g8emu
                  zip g8emu-macos-arm64.zip g8emu
                  rm g8emu

            - uses: actions/upload-artifact@v4
              with:
                  name: macos
                  path: g8emu-macos-arm64.zip

    release:
        runs-on: ubuntu-latest
        needs: [build-linux-windows, build-macos]
        steps:
            - uses: actions/download-artifact@v4
              with:
                  path: ./dist

            - uses: softprops/action-gh-release@v1
              with:
                  files: |
                      dist/linux-windows/g8emu-linux-amd64.zip
                      dist/linux-windows/g8emu-windows-amd64.zip
                      dist/macos/g8emu-macos-arm64.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
