name: Create Release

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v4
              with:
                  go-version: "1.23"

            - name: Install Linux dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev libasound2-dev

            - name: Build Windows
              run: |
                  GOOS=windows GOARCH=amd64 go build -o g8emu-windows.exe cmd/desktop/main.go

            - name: Build Linux
              run: |
                  GOOS=linux GOARCH=amd64 go build -o g8emu-linux cmd/desktop/main.go

            - name: Create Release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: |
                      g8emu-windows.exe
                      g8emu-linux
