name: Create Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    build:
        name: Build for ${{ matrix.label }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - label: linux-amd64
                      os: ubuntu-latest
                      goos: linux
                      goarch: amd64
                      output: g8emu-linux-amd64
                      deps: |
                          sudo apt-get update
                          sudo apt-get install -y \
                            libx11-dev \
                            libxcursor-dev \
                            libxrandr-dev \
                            libxinerama-dev \
                            libxi-dev \
                            libgl1-mesa-dev \
                            libasound2-dev \
                            libxxf86vm-dev
                    - label: windows-amd64
                      os: windows-latest
                      goos: windows
                      goarch: amd64
                      output: g8emu-windows-amd64.exe
                    - label: macos-amd64
                      os: macos-latest
                      goos: darwin
                      goarch: amd64
                      output: g8emu-macos-amd64
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v4
              with:
                  go-version: "1.23"
                  cache: true

            - name: Install dependencies (Linux only)
              if: runner.os == 'Linux'
              run: ${{ matrix.deps }}

            - name: Build binary
              run: |
                  GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
                  go build -o ${{ matrix.output }} cmd/desktop/main.go

            - uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.output }}
                  path: ${{ matrix.output }}

    release:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/download-artifact@v4
              with:
                  path: ./dist

            - uses: softprops/action-gh-release@v1
              with:
                  files: dist/**
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
